### ISSUE TITLE
[ZIP] Bug when extracting a jar file, folders are empty

### ISSUE THREAD

**Issue by rzaharia** [gdt050579/GView#243]
The file is from the [Minecraft Mod Just Enough Items](https://www.curseforge.com/minecraft/mc-mods/jei/download/5106178)

![image](https://github.com/gdt050579/GView/assets/13353201/8bddad1c-fa21-4501-986a-b069286f25c3)

**Comment by gheorghitamutu** [comment]
This is also related to https://github.com/gdt050579/GView/issues/185.
