### ISSUE TITLE
[Core] Make selection visible when PE panels are open

### ISSUE THREAD

**Issue by tanlorik** [gdt050579/GView#324]
When looking at a PE file with panels open (Sections, Directories, Resources) I like to select them to have a quick visual idea of how much space they take by pressing F9 while selecting each of them. However then a panel is open there is an overlay over the file that removes all colors. Please make is so selection are visible even with this overlay on.

~TAN

![gviewselection](https://github.com/user-attachments/assets/dca1ef5f-dfe5-49ca-a5d6-b220c4a8f0ff)

**Comment by gheorghitamutu** [comment]
Hello,
The current flow from GView is handled from [AppCUI](https://github.com/gdt050579/AppCUI) and it has been intentionally built to hide the information (selection, highlights, etc) when a panel is in focus.
I'd not say that we'll be changing this implementation but we'll explore and maybe make it configurable in some way (having as default the current behavior but being able to retain some information a user might need/want).

We'll look into it and come back with a proposal in the following weeks.

**Comment by gheorghitamutu** [comment]
> Hello, The current flow from GView is handled from [AppCUI](https://github.com/gdt050579/AppCUI) and it has been intentionally built to hide the information (selection, highlights, etc) when a panel is in focus. I'd not say that we'll be changing this implementation but we'll explore this idea and maybe make the behavior configurable in some way (having as default the current behavior but being able to retain some information a user might need/want).
> 
> We'll look into it and come back with a proposal in the following weeks.

I was wrong. The logic is built into BufferView. Will solve today.

**Comment by gheorghitamutu** [comment]
`Ctrl+Alt+C` to toggle the option. 
By default is set to true -> the selection and colors aren't grayed out anymore.
