### ISSUE TITLE
[DISSASM] x64 and x86 toggles are reversed

### ISSUE THREAD

**Issue by tanlorik** [gdt050579/GView#339]
**Desktop (please complete the following information):**
 - OS: Win11 [Version 10.0.22631.4169]
 - AppCUI Version: Version : 0.351.0

**Describe the bug**
The toggles for x64 and x86 are reversed in dissasm view

![gviewdisasm](https://github.com/user-attachments/assets/8b7d2d64-f59c-45bb-b2de-21d7b46f94d5)

**Comment by gheorghitamutu** [comment]
Fixed. Thank you, @tanlorik!
